DROP TABLE IF EXISTS ACLineSegment
;
DROP TABLE IF EXISTS ACLineSegmentPhase
;
DROP TABLE IF EXISTS Asset
;
DROP TABLE IF EXISTS AssetInfo
;
DROP TABLE IF EXISTS AssetInfoJoin
;
DROP TABLE IF EXISTS BaseVoltage
;
DROP TABLE IF EXISTS Breaker
;
DROP TABLE IF EXISTS ConcentricNeutralCableInfo
;
DROP TABLE IF EXISTS ConductingEquipment
;
DROP TABLE IF EXISTS ConnectivityNode
;
DROP TABLE IF EXISTS CoordinateSystem
;
DROP TABLE IF EXISTS Disconnector
;
DROP TABLE IF EXISTS EnergyConsumer
;
DROP TABLE IF EXISTS EnergyConsumerPhase
;
DROP TABLE IF EXISTS EnergySource
;
DROP TABLE IF EXISTS Fuse
;
DROP TABLE IF EXISTS GeographicalRegion
;
DROP TABLE IF EXISTS GroundedEndJoin
;
DROP TABLE IF EXISTS IEC61968CIMVersion
;
DROP TABLE IF EXISTS IEC61970CIMVersion
;
DROP TABLE IF EXISTS Jumper
;
DROP TABLE IF EXISTS Line
;
DROP TABLE IF EXISTS LinearShuntCompensator
;
DROP TABLE IF EXISTS LinearShuntCompensatorPhase
;
DROP TABLE IF EXISTS LoadBreakSwitch
;
DROP TABLE IF EXISTS LoadResponseCharacteristic
;
DROP TABLE IF EXISTS Location
;
DROP TABLE IF EXISTS NoLoadTest
;
DROP TABLE IF EXISTS OverheadWireInfo
;
DROP TABLE IF EXISTS PerLengthImpedance
;
DROP TABLE IF EXISTS PerLengthPhaseImpedance
;
DROP TABLE IF EXISTS PerLengthSequenceImpedance
;
DROP TABLE IF EXISTS PhaseCode
;
DROP TABLE IF EXISTS PhaseImpedanceData
;
DROP TABLE IF EXISTS PhaseShuntConnectionKind
;
DROP TABLE IF EXISTS PositionPoint
;
DROP TABLE IF EXISTS PowerSystemResource
;
DROP TABLE IF EXISTS PowerTransformer
;
DROP TABLE IF EXISTS PowerTransformerEnd
;
DROP TABLE IF EXISTS PowerTransformerInfo
;
DROP TABLE IF EXISTS RatioTapChanger
;
DROP TABLE IF EXISTS Recloser
;
DROP TABLE IF EXISTS RegulatingControl
;
DROP TABLE IF EXISTS RegulatingControlModeKind
;
DROP TABLE IF EXISTS Sectionaliser
;
DROP TABLE IF EXISTS ShortCircuitTest
;
DROP TABLE IF EXISTS SinglePhaseKind
;
DROP TABLE IF EXISTS SubGeographicalRegion
;
DROP TABLE IF EXISTS SvInjection
;
DROP TABLE IF EXISTS SvPowerFlow
;
DROP TABLE IF EXISTS SvShuntCompensatorSections
;
DROP TABLE IF EXISTS SvStatus
;
DROP TABLE IF EXISTS SvTapStep
;
DROP TABLE IF EXISTS SvVoltage
;
DROP TABLE IF EXISTS Switch
;
DROP TABLE IF EXISTS SwitchPhase
;
DROP TABLE IF EXISTS TapChangerControl
;
DROP TABLE IF EXISTS TapChangerInfo
;
DROP TABLE IF EXISTS TapeShieldCableInfo
;
DROP TABLE IF EXISTS Terminal
;
DROP TABLE IF EXISTS TopologicalIsland
;
DROP TABLE IF EXISTS TopologicalNode
;
DROP TABLE IF EXISTS TransformerControlMode
;
DROP TABLE IF EXISTS TransformerCoreAdmittance
;
DROP TABLE IF EXISTS TransformerEnd
;
DROP TABLE IF EXISTS TransformerEndInfo
;
DROP TABLE IF EXISTS TransformerMeshImpedance
;
DROP TABLE IF EXISTS TransformerTank
;
DROP TABLE IF EXISTS TransformerTankEnd
;
DROP TABLE IF EXISTS TransformerTankInfo
;
DROP TABLE IF EXISTS WindingConnection
;
DROP TABLE IF EXISTS WireInsulationKind
;
DROP TABLE IF EXISTS WirePosition
;
DROP TABLE IF EXISTS WireSpacingInfo
;
DROP TABLE IF EXISTS WireUsageKind
;
